In [1]:
import pandas as pd
import glob
import os

In [7]:
all_tender_path = r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-UP/Sources/TENDERS/data/all_tenders.csv'

In [3]:
#all_tender_path = r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\flood-data-ecosystem-UP\Sources\TENDERS\data/monthly_tenders'
all_tender_path = r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-UP/Sources/TENDERS/data/all_tenders.csv'

monthly_files = glob.glob(os.path.join(all_tender_path, '*.csv'))
up_tenders = pd.concat([pd.read_csv(f) for f in monthly_files], ignore_index=True)
# ensure Contract Date is datetime, then extract year_month
up_tenders['year_month'] = pd.to_datetime(up_tenders['Contract Date'], errors='coerce')
up_tenders['year_month'] = up_tenders['year_month'].dt.strftime('%Y_%m')
up_tenders.to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\flood-data-ecosystem-UP\Sources\TENDERS\data\all_UP_tenders.csv', index=False)
#up_tenders = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\flood-data-ecosystem-UP\Sources\TENDERS\data\floodtenders_blockgeotagged.csv')

ValueError: No objects to concatenate

In [8]:
up_tenders = pd.read_csv(all_tender_path)
up_tenders = up_tenders.loc[up_tenders['Status'] == 'Accepted-AOC']
up_tenders

/var/folders/mn/tyjcr2q91wz11fzw0ttcj3780000gn/T/ipykernel_83748/2598409411.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  up_tenders = pd.read_csv(all_tender_path)

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,Pincode,No of Bids Received,Tender Value in ₹,Bidder Name,Awarded Value,Status,Contract Date,Department,Contract Date :,year_month
34,2018_UPIDC_269394_6,01/EE/2018-19,Construcation of canal from km 14.575 to km 14...,Construcation of canal from km 14.575 to km 14...,Works,Open Tender,Item Wise,Civil Works - Canal,No,No,...,244302.0,2.0,"27,00,000",M/S DILSHAD AHMED,2336935.00,Accepted-AOC,2019-09-11,U P Irrigation Department (Civil)||Chief Engin...,NaN,NaN
35,2018_UPIDC_281416_3,04/EE/2018-19,Const of Panwasa DY. From km. 8.300 to 8.400 (...,Const of Panwasa DY. From km. 8.300 to 8.400,Works,Open Tender,Item Wise,Civil Works - Canal,No,No,...,244304.0,2.0,"11,00,000",AMIT KUMAR CONTRACTOR,659355.00,Accepted-AOC,2019-09-27,U P Irrigation Department (Civil)||Chief Engin...,NaN,NaN
36,2018_UPIDC_287991_6,07/EE/2018-19,Construction of Panwasa Dy. From km.2.800 to k...,Construction of Panwasa Dy. From km.2.800 to k...,Works,Open Tender,Item Wise,Civil Works - Canal,No,No,...,244304.0,2.0,"17,50,000",IQRAR AHMAD CONTRACTOR,1045640.00,Accepted-AOC,2019-09-07,U P Irrigation Department (Civil)||Chief Engin...,NaN,NaN
37,2019_CEUAZ_374005_1,2111 /SE Tender/Azamgarh Circle /19 DT. 09/08/...,Construction Work of New Bridge Approach Road ...,Construction Work of New Bridge Approach Road ...,Works,Open Tender,Fixed-rate,Civil Works,No,No,...,276001.0,2.0,"52,00,000",M/s Ajay Kumar Singh,4928912.00,Accepted-AOC,2019-09-18,"Chief Engineer PWD Azamgarh Zone,Azamgarh||S.E...",NaN,NaN
45,2019_MVVNL_375210_1,74/EDCB/2019-20,74/EDCB/2019-20,For Hiring of One No. Jeepshaped Diesel Vehicl...,Works,Open Tender,Item Rate,Electrical Works,No,No,...,243001.0,3.0,"2,65,000",M/S ZAHOOR TRADERS,264000.00,Accepted-AOC,2019-09-16,Madhyanchal Vidyut Vitran Nigam Ltd||C E - BAR...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51988,2020_UPRNS_443277_1,1112/E-Nivida/LucknowIII,Construction of 100MT Godown Sadhan Sahkari at...,Construction of 100MT Godown Sadhan Sahkari at...,Works,Open Tender,Percentage,Civil Works,No,No,...,241001.0,2.0,"23,75,000",M/S ANAND ENTERPRISES,2360750.00,Accepted-AOC,2020-03-18,Uttar Pradesh Rajya Nirman Sahkari Sangh Limited,NaN,NaN
52011,2020_UPRNS_445487_1,1376/NIVIDA/UPRNSS/GKP/2019-20 DT-07.03.20,CONSTRUCTION OF BOUNDARY WALL MS GATE AT GOVER...,BOUNDARY WALL MS GATE,Works,Open Tender,Percentage,Civil Works,No,No,...,274302.0,2.0,"16,57,000",KAMLA CONSTRUCTION,1656834.30,Accepted-AOC,2020-03-17,Uttar Pradesh Rajya Nirman Sahkari Sangh Limited,NaN,NaN
52012,2020_UPRNS_447955_1,50/WM/UPRNSS/Agra-II/2019-20,Contruction of Remaining work proposed Godown ...,Please See attached estimate,Works,Open Tender,Percentage,Civil Works,No,No,...,205001.0,2.0,"39,11,000",GIRJESH KUMARI,3907089.00,Accepted-AOC,2020-03-20,Uttar Pradesh Rajya Nirman Sahkari Sangh Limited,NaN,NaN
52014,2020_UPRNS_448012_1,919/E-Tender/64/Meerut-1/19-20,Remaining work of Antitermite Treatment for Di...,Remaining work of Antitermite Treatment for Di...,Works,Open Tender,Percentage,Civil Works,No,No,...,250001.0,2.0,"2,76,298",NATIVE CONCEPT,262958.00,Accepted-AOC,2020-03-21,Uttar Pradesh Rajya Nirman Sahkari Sangh Limited,NaN,NaN
52016,2020_UPSBC_423320_1,1786/ET/CPM/Agra/2019-20 Date 11.01.2020,"Construction of Approach Road, Additional Appr...","Construction of Approach Road, Additional Appr...",Works,Open Tender,Percentage,Civil Works - Bridges,No,No,...,283102.0,2.0,"1,16,94,063",M/S DHEER ENTERPRISES,8823170.98,Accepted-AOC,2020-03-07,UP STATE BRIDGE CORPORATION LIMITED||JMD UPSBC...,NaN,NaN

In [12]:
all_sum = up_tenders['Awarded Value'].sum()
all_sum

np.float64(25847637713.246998)

In [9]:
flood_tenders_all = pd.read_csv(r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-UP/Sources/TENDERS/data/flood_tenders_all.csv')

In [10]:
flood_tenders_all = flood_tenders_all.loc[flood_tenders_all['Status'] == 'Accepted-AOC']
sum = flood_tenders_all['Awarded Value'].str.replace(',','').astype(float).sum()
sum

np.float64(2176259930.131)

In [13]:
flood_tenders_all

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,negative_keywords_dict,Season,Scheme,Erosion,Roads_Bridges_Embkt,Response Type,Flood Response - Subhead,month,Contract Date :,year_month
3,2019_CEUAZ_374005_1,2111 /SE Tender/Azamgarh Circle /19 DT. 09/08/...,Construction Work of New Bridge Approach Road ...,Construction Work of New Bridge Approach Road ...,Works,Open Tender,Fixed-rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Monsoon,NaN,False,True,Repair and Restoration,"{'Construction': 2, 'Bridge': 4}",2019_09,NaN,NaN
4,2025_UPIDC_1083668_59,01/EE/2025-26,Silt Clearance/Scraping work of Lalpur Mr (Bet...,Silt Clearance/Scraping work of Lalpur Mr (Bet...,Works,Open Tender,Item Rate,Civil Works - Canal,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Repair and Restoration,{'mr': 2},2025_12,06-Dec-2025,NaN
5,2025_UPIDC_1083216_1,02 Date 08.10.2025 (Lot No-02),SILT CLEARANCE /SCRAPING AND JUNGLE CLEARANCE ...,SILT CLEARANCE /SCRAPING AND JUNGLE CLEARANCE,Works,Open Tender,Item Rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Others,NaN,2025_12,02-Dec-2025,NaN
6,2025_UPIDC_1086698_10,04/AE-IV/2025-26,Earth Work in Silt Clearance/Scraping of Chhat...,Silt Clearance/Scraping,Works,Open Tender,Item Rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,True,True,Repair and Restoration,{'mr': 2},2025_12,06-Dec-2025,NaN
7,2025_UPIDC_1088427_94,01/AE/2025-26,Lot-34,Silt clearance and Scraping,Works,Open Tender,Item Rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,True,True,Others,NaN,2025_12,26-Dec-2025,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5169,2020_CEUCZ_427563_1,367/e-tender/2020 dated 23.01.2020,Construction of Box Culvert on Connecting Road...,Construction of Box Culvert on Connecting Road...,Works,Open Tender,Fixed-rate,Civil Works - Roads,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Others,NaN,2020_03,NaN,NaN
5170,2020_CEUFZ_439158_1,1053/2com Ayo.Ambe.Circle/2020 Dated 24.02.2020,Construction of 5x5m span RCC culvert and 100m...,Construction of 5x5m span RCC culvert and 100m...,Works,Open Tender,Fixed-rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Others,NaN,2020_03,NaN,NaN
5171,2020_SCIDC_445400_1,86/76/MLC/Firozabad,FOR Construction of Nala from Culvert of Jalal...,FOR Construction of Nala from Culvert of Jalal...,Works,Open Tender,Percentage,Civil Works - Water Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Others,NaN,2020_03,NaN,NaN
5172,2020_UPIDC_426781_9,03/EE/Matatila/2019-20,Repairing of U/S boulder pitching,Repairing of U/S boulder pitching between leve...,Works,Open Tender,Item Rate,Civil Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Repair and Restoration,{'repairing': 2},2020_03,NaN,NaN
5173,2020_UPJNM_434564_1,319/ E TENDER/06 DT 06-02-2020,Complete repairing of 800mm x 800mm sluice gat...,Complete repairing of 800mm x 800mm sluice gat...,Works,Open Tender,Item Rate,Repair and Maintenance Works,No,No,...,"{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Repair and Restoration,{'repairing': 2},2020_03,NaN,NaN